app:
  swagger:
    basePackage: com.gjh.base.controller
    title: Base Framework Project RESTful APIs
    description: Base Framework
    serviceUrl: http://127.0.0.1:8080/api
    contact: guangjinhai@163.com
    version: 1.0